# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Programming Notes
email: sureshssarda@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Notes, articles and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sureshsarda.in" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  sureshsarda

# Build settings
markdown: kramdown
#theme: minima
# theme: "mmistakes/minimal-mistakes@master"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: sureshsarda/sureshsarda.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
minimal_mistakes_skin    : contrast # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
social:
  type: person
  name: Suresh Sarda
  links:
    - https://github.com/sureshsarda
    - https://stackoverflow.com/users/2149367/sureshs
    - https://www.linkedin.com/in/sureshsarda
    - https://angel.co/suresh-sarda
    - http://twitter.com/sureshssarda
    - https://www.facebook.com/suresh.sarda
    - https://www.quora.com/profile/Suresh-Sarda-1

analytics:
  provider: google
  google:
    tracking_id: UA-104753298-1

author:
  name             : "Suresh Sarda"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "print(suresh.bio)"
  location         : "Bangalore, India"
  email            : "sureshssarda@gmail.com"
  uri              :
  home             : "https://sureshsarda.in"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : suresh.sarda
  foursquare       :
  github           : sureshsarda
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : sureshsarda
  pinterest        :
  soundcloud       :
  stackoverflow    : 2149367/sureshs
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
