baseURL: '/'
languageCode: 'en-us'
title: 'suresh sarda'
theme: 'ananke'

menus:
  main:
    - name: essays
      url: '/'
    - name: notes
      url: '/notes'
    - name: about
      url: '/about'
    - name: reading
      url: '/reading' 
    

params:
  # featured_image: /images/white-texture.jpg
  background_color_class: bg-black
  production: true
  mainSections:
  - essays
  - reading
  ananke_socials:
    - name: twitter
      url: https://twitter.com/sureshssarda
    - name: github
      url: https://github.com/sureshsarda
    - name: linkedin
      url: https://www.linkedin.com/in/sureshsarda/
    - name: medium
      url: https://sureshssarda.medium.com/


markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4