baseURL: "/"
languageCode: "en-us"
title: "s9a.me"
theme: tailwind

menus:
  main:
    - name: home
      url: "/"
    # - name: notes
    #   url: '/notes'
    - name: about
      url: "/about"
    # - name: reading
    #   url: '/reading'
    - name: rss
      url: "/index.xml"
taxonomies:
  category: categories
  tags: tags

params:
  background_color_class: bg-black
  production: true
  description: s9a.me - my thoughts and ideas on programming
  images:
    - images/slipbox.jpg
  title: sureshsarda.me

  # mainSections:
  # - posts
  # - reading

  ananke_socials:
    - name: twitter
      url: https://twitter.com/sureshssarda
    - name: github
      url: https://github.com/sureshsarda
    - name: linkedin
      url: https://www.linkedin.com/in/sureshsarda/
    - name: medium
      url: https://sureshssarda.medium.com/

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 4

related:
  includeNewer: true
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 50
  - name: date
    weight: 10
  threshold: 80
  toLower: false

# disqusShortname: sardas
