baseURL: "/"
languageCode: "en-us"
title: "s9a.me"
theme: "ananke"

menus:
  main:
    - name: posts
      url: "/"
    # - name: notes
    #   url: '/notes'
    - name: about
      url: "/about"
    # - name: reading
    #   url: '/reading'
taxonomies:
  category: category
  tags: tags

params:
  background_color_class: bg-black
  production: true
  description: sureshsarda.me - my thoughts and ideas on programming
  images:
    - slipbox.jpg
  title: s9a.me

  # mainSections:
  # - posts
  # - reading

  ananke_socials:
    - name: twitter
      url: https://twitter.com/sureshssarda
    - name: github
      url: https://github.com/sureshsarda
    - name: linkedin
      url: https://www.linkedin.com/in/sureshsarda/
    - name: medium
      url: https://sureshssarda.medium.com/

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4

disqusShortname: sardas
